import { ClientProvider } from '@/components/shared/client-provider'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { MapProvider } from '../../providers/map-provider'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<ClientProvider>
					<MapProvider>{children}</MapProvider>
				</ClientProvider>
			</body>
		</html>
	)
}
